# Generated by Django 2.2.16 on 2022-03-19 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_title_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='com_pub_date',
            new_name='pub_date',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text_comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rev_pub_date',
            new_name='pub_date',
        ),
    ]
