# Generated by Django 2.2.16 on 2022-03-22 12:42

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0010_auto_20220320_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(validators=[api.validators.validate_year], verbose_name='Год выпуска'),
        ),
    ]
